ALTER TABLE course ALTER COLUMN cour_name NVARCHAR(20)

ALTER TABLE profession ALTER COLUMN pro_name NVARCHAR(20)

ALTER TABLE teacher ALTER COLUMN tea_name NVARCHAR(20)

ALTER TABLE student ALTER COLUMN stu_name NVARCHAR(20)